---
kind: pipeline
type: docker
name: default
steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
---
kind: signature
hmac: 2e287cc5c522d6dd31a62e59b8d5361ebe31229b42caf625f7d7fbc9314a19de

...
